---
# Task file for mysql_backup

- name: backup directory
  file:
    path: "{{ mysql_backup_directory }}"
    state: directory

- name: target script directory
  file:
    path: "{{ mysql_backup_target_script | dirname }}"
    state: directory

- name: target script template
  template:
    src: templates/mysql_backup_target.sh.j2
    dest: "{{ mysql_backup_target_script }}"
    mode: 0755
    force: true

- name: docker container
  when: mysql_backup_compose == false
  docker_container:
    name: "{{ mysql_backup_container_name }}"
    image: "{{ mysql_backup_container_image }}"
    recreate: true
    state: started
    container_default_behavior: no_defaults
    networks_cli_compatible: no
    restart_policy: "{{ mysql_backup_container_restart_policy }}"
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    env:
      TZ: "{{ timezone }}"
      DB_SERVER: "{{ mysql_backup_server }}"
      DB_USER: "{{ mysql_backup_user }}"
      DB_PASS: "{{ mysql_backup_password }}"
      # DB_DUMP_CRON: "{{ mysql_backup_cron }}"
      DB_DUMP_TARGET: /backups 
      NICE: "{{ mysql_backup_nice }}"
    user: "0"
    volumes:
      - "{{ mysql_backup_directory }}:/backups"
      - "{{ mysql_backup_target_script }}:/scripts.d/target.sh"
      - "/etc/timezone:/etc/timezone:ro"
    networks:
      - name: "{{ mysql_backup_network_name }}"
