---
# task file for mealie

- name: data directory
  file:
    path: "{{ mealie_data_directory }}"
    state: directory
    owner: "{{ mealie_uid }}"
    group: "{{ mealie_gid }}"

- name: compose
  docker_compose:
    project_name: "{{ mealie_project_name }}"
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    definition:
      version: "3.5"
      networks:
        traefik_public:
          external: true
      services:
        mealie:
          container_name: "{{ mealie_container_name }}"
          image: "{{ mealie_container_image }}"
          restart: "{{ mealie_restart_policy }}"
          volumes:
            - "{{ mealie_data_directory }}:/app/data"
            - "/etc/localtime:/etc/localtime:ro"
          environment:
            - "TZ={{ timezone }}"
            - "PUID={{ mealie_uid }}"
            - "PGID={{ mealie_gid }}"
            - "DEFAULT_EMAIL={{ email_address }}"
            - "RECIPE_PUBLIC={{ mealie_recipe_public }}"
          labels:
            - "traefik.enable={{ mealie_expose }}"
            - "traefik.http.routers.mealie.tls=true"
            - "traefik.http.routers.mealie.rule={{ mealie_traefik_rule }}"
            - "traefik.http.routers.mealie.tls.certresolver=letsencrypt"
            - "traefik.http.routers.mealie.middlewares=frame-allow@file"
            - "traefik.http.services.mealie.loadbalancer.server.port=80"
          networks:
            - traefik_public
