---
# task file for mealie

- name: data directory
  file:
    path: "{{ mealie_data_directory }}"
    state: directory
    owner: "{{ mealie_uid }}"
    group: "{{ mealie_gid }}"

- name: compose
  docker_compose:
    project_name: "{{ mealie_project_name }}"
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    definition:
      version: "3.5"
      networks:
        traefik_public:
          external: true
        mealie:
          name: mealie
          driver: overlay
          internal: true
        mail:
          external: true
      services:
        mealie-frontend:
          image: "{{ mealie_frontend_container_image }}"
          container_name: mealie-frontend
          depends_on:
            - mealie-api
          environment:
            - "API_URL=http://mealie-api:9000"
          restart: "{{ mealie_frontend_restart_policy }}"
          volumes:
            - "{{ mealie_data_directory }}:/app/data"
            - "/etc/localtime:/etc/localtime:ro"
          labels:
            - "traefik.enable={{ mealie_expose }}"
            - "traefik.http.routers.mealie.tls=true"
            - "traefik.http.routers.mealie.rule={{ mealie_traefik_rule }}"
            - "traefik.http.routers.mealie.tls.certresolver=letsencrypt"
            - "traefik.http.routers.mealie.middlewares=frame-allow@file"
            - "traefik.http.services.mealie.loadbalancer.server.port=3000"
          networks:
            - mealie
            - traefik_public
        mealie-api:
          image: "{{ mealie_api_container_image }}"
          container_name: mealie-api
          volumes:
            - "{{ mealie_data_directory }}:/app/data"
            - "/etc/localtime:/etc/localtime:ro"
          environment:
            - "TZ={{ timezone }}"
            - "PUID={{ mealie_uid }}"
            - "PGID={{ mealie_gid }}"
            - "DEFAULT_EMAIL={{ email_address }}"
            - "RECIPE_PUBLIC={{ mealie_recipe_public }}"
            - "ALLOW_SIGNUP={{ mealie_allow_signup }}"
            - "BASE_URL={{ mealie_base_url }}"
            - "SMTP_HOST={{ mealie_smtp_host }}"
            - "SMTP_PORT={{ mealie_smtp_port }}"
            - "SMTP_FROM_EMAIL={{ mealie_smtp_from_email }}"
            - "SMTP_FROM_NAME={{ mealie_smtp_from_name }}"
            - "SMTP_AUTH_STRATEGY=NONE"
            - "TOKEN_TIME={{ mealie_token_time }}"
          restart: "{{ mealie_api_restart_policy }}"
          networks:
            - mealie
            - mail
