---
# defaults file for nextcloud

nextcloud_container_name: nextcloud
nextcloud_container_image: "nextcloud"
nextcloud_traefik_rule: "Host(`nextcloud.{{ domain }}`)"
nextcloud_expose: "true"
nextcloud_runtime_directory: "{{ base_runtime_directory }}/nextcloud"
nextcloud_data_directory: "{{ base_data_directory }}/nextcloud"
nextcloud_storage_directory: "{{ nextcloud_data_directory }}/data"
nextcloud_mysql_root_password: "{{ lookup('password', 'credentials/nextcloud/mysql_root_password length=64') }}"
nextcloud_mysql_password: "{{ lookup('password', 'credentials/nextcloud/mysql_password length=64') }}"
nextcloud_network_name: nextcloud
nextcloud_db_container_image: mariadb:10
nextcloud_redis_container_image: redis:alpine
nextcloud_basic_volumes:
      - "{{ nextcloud_runtime_directory }}/html:/var/www/html"
      - "{{ nextcloud_data_directory }}/apps:/var/www/html/custom_apps"
      - "{{ nextcloud_data_directory }}/config:/var/www/html/config"
      - "{{ nextcloud_storage_directory }}:/var/www/html/data"
nextcloud_extra_volumes: []
nextcloud_all_volumes: "{{ (nextcloud_basic_volumes + nextcloud_extra_volumes) | list }}"
