---
# task file for jellyfin

- name: directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ media_uid }}"
    group: "{{ media_gid }}"
  loop:
    - "{{ jellyfin_runtime_directory }}/cache"
    - "{{ jellyfin_runtime_directory }}/log"
    - "{{ jellyfin_runtime_directory }}/metadata"
    - "{{ jellyfin_runtime_directory }}/transcoding-temp"
    - "{{ jellyfin_runtime_directory }}/transcodes"
    - "{{ jellyfin_data_directory }}"
    - "{{ media_movies_directory }}"
    - "{{ media_series_directory }}"

- name: compose
  docker_compose:
    project_name: "{{ jellyfin_project_name }}"
    definition:
      version: "3.5"
      networks:
        traefik_public:
          external: true
        mail:
          external: true
      services:
        jellyfin:
          container_name: "{{ jellyfin_container_name }}"
          image: "{{ jellyfin_container_image }}"
          restart: "{{ jellyfin_restart_policy }}"
          environment:
            - "TZ={{ timezone }}"
            - "PUID={{ media_uid }}"
            - "PGID={{ media_gid }}"
          volumes:
            - /etc/localtime:/etc/localtime:ro
            - "{{ jellyfin_runtime_directory }}/cache:/cache"
            - "{{ jellyfin_runtime_directory }}/log:/config/log"
            - "{{ jellyfin_runtime_directory }}/metadata:/config/metadata"
            - "{{ jellyfin_runtime_directory }}/transcoding-temp:/config/tanscoding-temp"
            - "{{ jellyfin_runtime_directory }}/transcodes:/config/transcodes"
            - "{{ jellyfin_data_directory }}:/config"
            - "{{ media_movies_directory }}:/mnt/library/Movies:ro"
            - "{{ media_series_directory }}:/mnt/library/Series:ro"
          labels:
            - "traefik.enable={{ jellyfin_expose }}"
            - "traefik.http.routers.jellyfin.tls=true"
            - "traefik.http.routers.jellyfin.rule={{ jellyfin_traefik_rule }}"
            - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
            - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
          networks:
            - traefik_public
            - mail
