---
# defaults file for jellyfin

jellyfin_project_name: "{{ media_project_name }}"
jellyfin_container_name: jellyfin
jellyfin_container_image: "ghcr.io/hotio/jellyfin:release"
jellyfin_restart_policy: unless-stopped
jellyfin_traefik_rule: "Host(`jellyfin.{{ domain }}`)"
jellyfin_expose: "true"
jellyfin_data_directory: "{{ base_data_directory }}/jellyfin"
jellyfin_runtime_directory: "{{ base_runtime_directory }}/jellyfin"
jellyfin_devices: []
