---
# tasks file for mqtt

- name: directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ mosquitto_data_directory }}/config"
    - "{{ mosquitto_data_directory }}/data"
    - "{{ mosquitto_runtime_directory }}/logs"

- name: config file
  copy:
    src: mosquitto.conf
    dest: "{{ mosquitto_data_directory }}/config/mosquitto.conf"
    force: yes

- name: compose
  docker_compose:
    project_name: "{{ mosquitto_project_name }}"
    definition:
      version: "3.5"
      networks:
        mqtt:
          external: true
      services:
        mosquitto:
          container_name: "{{ mosquitto_container_name }}"
          image: "{{ mosquitto_container_image }}"
          restart: "{{ mosquitto_restart_policy }}"
          environment:
            - "TZ={{ timezone }}"
          ports:
            - 1883:1883
          volumes:
            - "{{ mosquitto_data_directory }}/config:/mosquitto/config"
            - "{{ mosquitto_data_directory }}/data:/mosquitto/data"
            - "{{ mosquitto_runtime_directory }}/logs:/mosquitto/logs"
          networks:
            - mqtt
