---
# task file for netdata

- name: netdata data directory
  file:
    path: "{{ netdata_data_directory }}/etc"
    state: directory
  loop:
    - "{{ netdata_data_directory }}/etc"
    - "{{ netdata_data_directory }}/orig"

- name: docker gid
  group:
    name: docker
  register: docker_group

- name: netdata docker container
  docker_container:
    name: "{{ netdata_container_name }}"
    image: "{{ netdata_container_image }}"
    recreate: true
    state: started
    container_default_behavior: no_defaults
    networks_cli_compatible: no
    restart_policy: unless-stopped
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    env:
      TZ: "{{ timezone }}"
      PGID: "{{ docker_group.gid }}"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - "{{ docker_socket_path }}:{{ docker_socket_path }}:ro"
    capabilities:
      - SYS_PTRACE
    security_opts:
      - apparmor:unconfined
    labels:
      traefik.enable: "{{ netdata_expose }}"
      traefik.http.routers.netdata.tls: "true"
      traefik.http.routers.netdata.rule: "{{ netdata_traefik_rule }}"
      traefik.http.routers.netdata.middlewares: fauth@file
      traefik.http.routers.netdata.tls.certresolver: letsencrypt
      traefik.http.services.netdata.loadbalancer.server.port: "19999"
    networks:
      - name: "{{ traefik_network_name }}"
      - name: "{{ mail_network_name }}"
