---
# defaults file for tvheadend

tvheadend_project_name: tvheadend
tvheadend_container_name: tvheadend
tvheadend_container_image: "linuxserver/tvheadend:latest"
tvheadend_restart_policy: unless-stopped
tvheadend_base_data_directory: "{{ base_data_directory }}/tvheadend"
tvheadend_config_directory: "{{ tvheadend_base_data_directory }}/config"
tvheadend_recordings_directory: "{{ tvheadend_base_data_directory }}/recordings"
tvheadend_timeshift_directory: "{{ tvheadend_base_data_directory }}/timeshift"
tvheadend_tvicons_directory: "{{ tvheadend_base_data_directory }}/timeshift"
tvheadend_uid: "0"
tvheadend_gid: "0"
tvheadend_expose: "true"
tvheadend_traefik_rule: "Host(`tvheadend.{{ domain }}`)"
xmltv_traefik_rule: "Host(`xmltv.{{ domain }}`)"
