---
# task file for guacamole

- name: data directory
  file:
    path: "{{ guacamole_data_directory }}"
    state: directory

- name: compose
  docker_compose:
    project_name: "{{ guacamole_project_name }}"
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    definition:
      version: "3.5"
      networks:
        traefik_public:
          external: true
      services:
        guacamole:
          container_name: "{{ guacamole_container_name }}"
          image: "{{ guacamole_container_image }}"
          restart: "{{ guacamole_restart_policy }}"
          environment:
            - "TZ={{ timezone }}"
          volumes:
            - "{{ guacamole_data_directory }}:/config"
          labels:
            - "traefik.enable={{ guacamole_expose }}"
            - "traefik.http.routers.guacamole.tls=true"
            - "traefik.http.routers.guacamole.rule={{ guacamole_traefik_rule }}"
            - "traefik.http.routers.guacamole.tls.certresolver=letsencrypt"
            - "traefik.http.services.guacamole.loadbalancer.server.port=8080"
          networks:
            - traefik_public
