---
# task file for samba

# - name: Create Samba users if they don't exist yet
#   shell: >
#     set -o nounset -o pipefail -o errexit &&
#     (pdbedit --user={{ item.name }} 2>&1 > /dev/null) \
#     || (echo {{ item.password }}; echo {{ item.password }}) \
#     | smbpasswd -s -a {{ item.name }}
#   args:
#     executable: /bin/bash
#   with_items: "{{ samba_users }}"
#   register: create_user_output
  # changed_when: "'Added user' in create_user_output.stdout"

- name: set up shares
  include_role:
    name: bertvv.samba
  vars:
    no_log: false
