---
# defaults file for traefik

traefik_project_name: traefik

duckdns_container_name: duckdns
duckdns_container_image: "linuxserver/duckdns:latest"
duckdns_restart_policy: unless-stopped

boreale_container_name: boreale
boreale_container_image: "phha/boreale:latest"
boreale_page_title: Authentication
boreale_data_directory: "{{ base_data_directory }}/boreale"
boreale_restart_policy: unless-stopped
boreale_users:
  - username: my_first_user
    password: "{{ lookup('password', 'credentials/boreale/my_first_user_password length=24') }}"
  - username: my_second_user
    password: "{{ lookup('password', 'credentials/boreale/my_second_user_password length=24') }}"

traefik_container_name: traefik
traefik_container_image: "traefik:latest"
traefik_data_directory: "{{ base_data_directory }}/traefik"
traefik_log_level: INFO
traefik_access_log: false
traefik_network_name: traefik_public
traefik_expose: "true"
traefik_restart_policy: unless-stopped

traefik_public_subnet: 10.0.2.0/24
traefik_public_gateway: 10.0.2.1
trefik_public_iprange: 10.0.2.0/26

letsencrypt_email_address: "{{ email_address }}"

extra_routes: {}
