---
# task file for calibre

- name: data directory
  file:
    path: "{{ calibre_data_directory }}"
    state: directory
    owner: "{{ media_user.uid }}"
    group: "{{ media_user.group }}"

- name: compose
  docker_compose:
    project_name: "{{ calibre_project_name }}"
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    definition:
      version: "3.5"
      services:
        calibre:
          container_name: "{{ calibre_container_name }}"
          image: "{{ calibre_container_image }}"
          restart: "{{ calibre_restart_policy }}"
          environment:
            - "TZ={{ timezone }}"
            - "PUID={{ media_user.uid }}"
            - "PGID={{ media_user.group }}"
            - "UMASK={{ media_umask }}"
            - "UMASK_SET={{ media_umask }}"
          volumes:
            - "{{ calibre_data_directory }}:/config"
            - "{{ media_directory }}/media/books:/data/media/books"
          labels:
            - "traefik.enable={{ calibre_expose }}"
            - "traefik.http.routers.calibre.tls=true"
            - "traefik.http.routers.calibre.rule={{ calibre_traefik_rule }}"
            - "traefik.http.routers.calibre.middlewares=fauth@file"
            - "traefik.http.routers.calibre.tls.certresolver=letsencrypt"
            - "traefik.http.routers.calibre.service=calibre"
            - "traefik.http.services.calibre.loadbalancer.server.port=8080"
            - "traefik.http.routers.calibre_ui.tls=true"
            - "traefik.http.routers.calibre_ui.rule={{ calibre_ui_traefik_rule }}"
            - "traefik.http.routers.calibre_ui.middlewares=fauth@file"
            - "traefik.http.routers.calibre_ui.tls.certresolver=letsencrypt"
            - "traefik.http.routers.calibre_ui.service=calibre_ui"
            - "traefik.http.services.calibre_ui.loadbalancer.server.port=8081"
          networks:
            - traefik_public
            - internal
            - mail
      networks:
        traefik_public:
          external: true
        internal:
          external: true
        mail:
          external: true
