---
# task file for readarr

- name: data directory
  file:
    path: "{{ readarr_data_directory }}"
    state: directory

- name: compose
  docker_compose:
    project_name: "{{ readarr_project_name }}"
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    definition:
      version: "3.5"
      networks:
        traefik_public:
          external: true
        mail:
          external: true
      services:
        readarr:
          container_name: "{{ readarr_container_name }}"
          image: "{{ readarr_container_image }}"
          restart: "{{ readarr_restart_policy }}"
          environment:
            - "TZ={{ timezone }}"
            - "PUID={{ media_uid }}"
            - "PGID={{ media_gid }}"
            - "DEBUG=true"
          volumes:
            - "{{ readarr_data_directory }}:/config"
            - "{{ media_books_directory }}:/books"
            - "{{ media_audiobooks_directory }}:/audiobooks"
            - "{{ media_magazines_directory }}:/magazines"
            - "{{ media_comics_directory }}:/comics"
            - "{{ shared_directory }}:/alternate:ro"
            - "{{ media_download_directory }}/complete/books:/downloads"
          labels:
            - "traefik.enable={{ readarr_expose }}"
            - "traefik.http.routers.readarr.tls=true"
            - "traefik.http.routers.readarr.rule={{ readarr_traefik_rule }}"
            - "traefik.http.routers.readarr.middlewares=fauth@file"
            - "traefik.http.routers.readarr.tls.certresolver=letsencrypt"
            - "traefik.http.services.readarr.loadbalancer.server.port=8787"
          networks:
            - traefik_public
            - mail
