---
# task file for readarr

- name: Create readarr data directory
  file:
    path: "{{ readarr_data_directory }}"
    state: directory

- name: readarr docker container
  docker_container:
    name: "{{ readarr_container_name }}"
    image: "{{ readarr_container_image }}"
    recreate: true
    state: started
    container_default_behavior: no_defaults
    networks_cli_compatible: no
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    env:
      TZ: "{{ timezone }}"
      PUID: "{{ media_uid }}"
      PGID: "{{ media_gid }}"
      DEBUG: "true"
    volumes:
      - "{{ readarr_data_directory }}:/config"
      - "{{ media_books_directory }}:/books"
      - "{{ media_audiobooks_directory }}:/audiobooks"
      - "{{ media_magazines_directory }}:/magazines"
      - "{{ media_comics_directory }}:/comics"
      - "{{ shared_directory }}:/alternate:ro"
      - "{{ media_download_directory }}/complete/books:/downloads"
    labels:
      traefik.enable: "{{ readarr_expose }}"
      traefik.http.routers.readarr.tls: "true"
      traefik.http.routers.readarr.rule: "{{ readarr_traefik_rule }}"
      traefik.http.routers.readarr.middlewares: fauth@file
      traefik.http.routers.readarr.tls.certresolver: letsencrypt
      traefik.http.services.readarr.loadbalancer.server.port: "8787"
    networks:
      - name: "{{ traefik_network_name }}"
      - name: "{{ internal_network_name }}"
      - name: "{{ mail_network_name }}"
