---
# task file for radarr

- name: data directory
  file:
    path: "{{ radarr_data_directory }}"
    state: directory
    owner: "{{ media_user.uid }}"
    group: "{{ media_user.group }}"

- name: compose
  docker_compose:
    project_name: "{{ radarr_project_name }}"
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    definition:
      version: "3.5"
      networks:
        traefik_public:
          external: true
        mail:
          external: true
        media:
          external: true
      services:
        radarr:
          container_name: "{{ radarr_container_name }}"
          image: "{{ radarr_container_image }}"
          restart: "{{ radarr_restart_policy }}"
          environment:
            - "TZ={{ timezone }}"
            - "PUID={{ media_user.uid }}"
            - "PGID={{ media_user.group }}"
            - "UMASK={{ media_umask }}"
          volumes:
            - "{{ radarr_data_directory }}:/config"
            - "{{ media_directory }}:/data"
            - "{{ shared_directory }}:/shared:ro"
          labels:
            - "traefik.enable={{ radarr_expose }}"
            - "traefik.http.routers.radarr.tls=true"
            - "traefik.http.routers.radarr.rule={{ radarr_traefik_rule }}"
            - "traefik.http.routers.radarr.middlewares=fauth@file"
            - "traefik.http.routers.radarr.tls.certresolver=letsencrypt"
            - "traefik.http.services.radarr.loadbalancer.server.port=7878"
          networks:
            - traefik_public
            - mail
            - media
