---
# tasks file for tvheadend

- name: directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ media_user.uid }}"
    group: "{{ media_user.group }}"
    mode: 0755
  loop:
    - "{{ tvheadend_config_directory }}"
    - "{{ tvheadend_recordings_directory }}"
    - "{{ tvheadend_timeshift_directory }}"
    - "{{ tvheadend_tvicons_directory }}"

- name: Mobile UI
  synchronize:
    src: mobile
    dest: "{{ tvheadend_base_data_directory }}"
    delete: true
    checksum: true
    archive: false
    recursive: true

- name: TVHadmin
  synchronize:
    src: TVHadmin-JS
    dest: "{{ tvheadend_base_data_directory }}"
    delete: true
    checksum: true
    archive: false
    recursive: true

- name: compose
  docker_compose:
    project_name: "{{ tvheadend_project_name }}"
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    definition:
      version: "3.5"
      services:
        tvheadend:
          container_name: "{{ tvheadend_container_name }}"
          image: "{{ tvheadend_container_image }}"
          restart: "{{ tvheadend_restart_policy }}"
          environment:
            - "TZ={{ timezone }}"
            - "PUID={{ media_user.uid }}"
            - "PGID={{ media_user.group }}"
            - "UMASK={{ media_umask }}"
            - "RUN_OPTS=--noacl"
          volumes:
            - "{{ tvheadend_config_directory }}:/config"
            - "{{ tvheadend_recordings_directory }}:/recordings"
            - "{{ tvheadend_timeshift_directory }}:/timeshift"
            - "{{ tvheadend_tvicons_directory }}:/tvicons:ro"
            - "{{ tvheadend_base_data_directory }}/mobile:/usr/share/tvheadend/src/webui/static/mobile:ro"
            - "{{ tvheadend_base_data_directory }}/TVHadmin-JS:/usr/share/tvheadend/src/webui/static/TVHadmin-JS"
          labels:
            - "traefik.enable={{ tvheadend_expose }}"
            - "traefik.http.routers.tvheadend.tls=true"
            - "traefik.http.routers.tvheadend.rule={{ tvheadend_traefik_rule }}"
            - "traefik.http.routers.tvheadend.middlewares=fauth@file"
            - "traefik.http.routers.tvheadend.tls.certresolver=letsencrypt"
            - "traefik.http.services.tvheadend.loadbalancer.server.port=9981"
            - "traefik.http.routers.xmltv.tls=true"
            - "traefik.http.routers.xmltv.rule={{ xmltv_traefik_rule }}"
            - "traefik.http.routers.xmltv.middlewares=xmltv-add-prefix@docker"
            - "traefik.http.routers.xmltv.tls.certresolver=letsencrypt"
            - "traefik.http.middlewares.xmltv-add-prefix.addprefix.prefix=/xmltv/channels"
            - "traefik.http.routers.xmltv.service=tvheadend"
          network_mode: host
          extra_hosts:
            "host.docker.internal": "{{ host_ip }}"
