
---
# task file for elkarbackup

- name: directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ elkarbackup_db_directory }}"
    - "{{ elkarbackup_uploads_directory }}"
    - "{{ elkarbackup_ssh_directory }}"
    - "{{ elkarbackup_backups_directory }}"

- name: db backup
  include_role:
    name: mysql_backup
    public: yes
  vars:
    mysql_backup_password: "{{ elkarbackup_mysql_root_password }}"
    mysql_backup_compose: true

- name: compose
  docker_compose:
    project_name: "{{ elkarbackup_project_name }}"
    definition:
      version: "3.5"
      networks:
        elkarbackup:
          internal: true
          driver: overlay
        traefik_public:
          external: true
        mail:
          external: true
      services:
        db:
          container_name: "{{ elkarbackup_db_container_name }}"
          image: "{{ elkarbackup_db_container_image }}"
          restart: "{{ elkarbackup_db_container_restart_policy }}"
          environment:
            - "TZ={{ timezone }}"
            - "MYSQL_ROOT_PASSWORD={{ elkarbackup_mysql_root_password }}"
          volumes:
            - "{{ elkarbackup_runtime_directory }}/db:/var/lib/mysql"
          networks:
            - elkarbackup
        # db_backup: "{{ mysql_backup_definition | to_yaml(width=9999) }}"
        db_backup: "{{ mysql_backup_definition }}"
        elkarbackup:
          container_name: "{{ elkarbackup_container_name }}"
          image: "{{ elkarbackup_container_image }}"
          restart: "{{ elkarbackup_restart_policy }}"
          environment:
            - "TZ={{ timezone }}"
            - "PHP_TZ={{ timezone }}"
            - "SYMFONY__MAILER__HOST=mail"
            - "SYMFONY__MAILER__FROM={{ email_address }}"
            - "SYMFONY__DATABASE__HOST={{ elkarbackup_db_container_name }}"
            - "SYMFONY__DATABASE__PASSWORD={{ elkarbackup_mysql_root_password }}"
            - "EB_CRON=enabled"
          volumes: "{{ elkarbackup_all_volumes }}"
          labels:
            - "traefik.enable={{ elkarbackup_expose }}"
            - "traefik.http.routers.elkarbackup.tls=true"
            - "traefik.http.routers.elkarbackup.rule={{ elkarbackup_traefik_rule }}"
            - "traefik.http.routers.elkarbackup.tls.certresolver=letsencrypt"
            - "traefik.http.services.elkarbackup.loadbalancer.server.port=80"
          networks:
            - traefik_public
            - elkarbackup
            - mail

