---

# Example variable file. Copy the entire "inventories-example" folder to
# "inventory/" and edit as needed.
# This example file only contains variables that absolutely need to be set or
# that are common overrides. However ,there are many more variables that are already
# set to sensible defaults. Should you want to override these variables, you
# can do so here as well. Please take a look into the defaults folder of the
# individual roles for available vars.

# Common
timezone: Europe/Berlin
base_directory: /srv/docker
base_data_directory: "{{ base_directory }}/data"
base_runtime_directory: "{{ base_directory }}/runtime"
shared_directory: "{{ base_directory }}/shared"
prune: true

# Backups
db_backups_enabled: true
db_backups_directory: /srv/docker/backups/db
db_backups_cron: "0 21 * * *" # UTC
duplicati_enabled: true
duplicati_extra_volumes:
  - "/home/myuser:/source/myuser:ro"
  - "{{ media_directory }}/media/books:/source/books:ro"
  - "{{ paperless_ng_export_directory }}:/source/documents:ro"

# Common Networking
host_ip: 192.168.0.2
domain: my-domain.duckdns.org
email_address: my-email@gmail.com
duckdns_token: Improve-Craving-Clumsy-Disobey
boreale_users:
  - username: my_first_user
    password: Mushiness-Stylishly-Wieldable-Aftermath
  - username: my_second_user
    password: Sermon-Enrage-Overprice-Steerable

# Extra routes
extra_routes:
  my-home-router:
    url: https://192.168.0.1
    auth: true # optional default true
    rule: "Host(`router.{{ domain }}`)" # optional default <key>.<domain>
  my-other-web-server:
    url: http://192.168.2.94:80

# mail
mail_enabled: true
mail_relay_host: "[smtp.gmail.com]:587"
mail_relay_user: "{{ email_address }}"
mail_relay_password: Nanny-Reassign-Snowbound-Strep

# Common Media
media_directory: /mnt/storage/media_data

# Home Assistant
homeassistant_enabled: true

# Node-Red
nodered_enabled: true

# MQTT
mqtt_enabled: true

# Zigbee
zigbee_enabled: true
zigbee_device: /dev/ttyACM0

# TVHeadend
tvheadend_enabled: true
tvheadend_recordings_directory: /mnt/storage/recordings
tvheadend_timeshift_directory: /mnt/storage/timeshift
tvheadend_tvicons_directory: /mnt/storage/tvicons
tvheadend_uid: "108"
tvheadend_gid: "112"

# pihole
pihole_enabled: true
pihole_password: Amid-Refining-Pretext-Acrobat
pihole_extra_hosts:
  home.router: 192.168.0.1
  some-host.local: 192.168.0.2

# portainer
portainer_enabled: true
portainer_admin_password: Smooth-Pacific-Tractor-Monsoon

# sonarr
sonarr_enabled: true

# lidarr
lidarr_enabled: true

# radarr
radarr_enabled: true

# readarr
readarr_enabled: true

# torrent
torrent_vpn_enabled: "true"
torrent_wireguard: |
  [Interface]
  PrivateKey = supersecretprivatekey
  Address = xx.xx.xxx.xxx/32
  DNS = 1.1.1.1

  [Peer]
  PublicKey = publickey
  AllowedIPs = 0.0.0.0/0
  Endpoint = xxx.x.xxx.x:51820

# ombi
ombi_enabled: true

# calibre_web
calibre_web_enabled: true

# calibre
calibre_enabled: true

# paperless-ng
paperless_ng_enabled: true
paperless_ng_superuser_name: admin
paperless_ng_superuser_password: "{{ lookup('password', 'credentials/paperless_ng/superuser-password length=64') }}"

# guacamole
guacamole_enabled: true

# nextcloud
nextcloud_enabled: true
nextcloud_admin_user: admin
nextcloud_admin_pass: Linked-Transform-Antitrust-Reissue
nextcloud_storage_directory: /mnt/storage/nextcloud
nextcloud_extra_volumes:
  - "/some/dir:/external/Documents"
  - "{{ tvheadend_recordings_directory }}:/external/recordings:ro"
  - "{{ media_directory }}/media:/external/media:ro"
  - "{{ paperless_ng_media_directory }}:/external/paperless:ro"
  - "{{ shared_directory }}:/external/shared:rw"

# unmanic
unmanic_enabled: true

# jellyfin
jellyfin_enabled: true
jellyfin_devices:
  - /dev/dri:/dev/dri

# influxdb
influxdb_enabled: true

# grafana
grafana_enabled: true
grafana_plugins: neocat-cal-heatmap-panel,snuids-trafficlights-panel,natel-discrete-panel,natel-plotly-panel

# organizr
organizr_enabled: true

# elkarbackup
elkarbackup_enabled: true
elkarbackup_backups_directory: /mnt/storage/elkarbackup
elkarbackup_extra_volumes:
  - "{{ media_directory }}/media:/sources/media:ro"
  - "{{ paperless_ng_export_directory }}:/sources/paperless:ro"

# netdata
netdata_enabled: true

# Gitea
gitea_enabled: true
gitea_app_name: "Gitea: Git with a cup of tea"
gitea_ssh_port: "1222"
gitea_lfs: "false"
gitea_disable_registration: "true"
gitea_require_signin: "true"

# Wireguard
wireguard_enabled: true
wireguard_peers: "my_phone,my_notebook"

# Jupyter
jupyter_enabled: true

# Diun
diun_enabled: true
# diun_notifier:
#   telegram:
#     token: "abcd:1234"
#     chatIDs:
#       - "1337"

# Wallabag
wallabag_enabled: true
wallabag_admin_password: Nucleus-Gathering-Glacier-Petted

# Wallabag Kindle Consumer
wallabag_kindle_enabled: true
wallabag_kindle_client_id: Slept-Persuaded-Prissy-Tabasco
wallabag_kindle_client_secret: Lurch-Imprudent-Prevalent-Bluish

# Firefox
firefox_enabled: true

# Joplin
joplin_enabled: true

# ELK stack
elk_enabled: true

# piknik
piknik_enabled: true

# webtop
webtop_enabled: true

# miniflux
miniflux_enabled: true
miniflux_admin_username: admin
miniflux_admin_password: "{{ lookup('password', 'credentials/miniflux/admin_password length=64') }}"

# Samba
samba_enabled: true
samba_shares_root: "{{ base_directory }}/samba_shares"
samba_load_homes: true
samba_netbios_name: "{{ ansible_hostname }}"
samba_users:
  - name: myuser
    password: mypassword
samba_shares:
  - name: media
    comment: Media
    guest_ok: true
    browseable: true
    public: true
    writable: false
    path: "{{ media_directory }}/media"
    owner: "{{ media_user.user }}"
    group: "{{ media_user.gid }}"
  - name: recordings
    comment: TV recordings
    guest_ok: true
    browseable: true
    public: true
    writable: false
    path: "{{ tvheadend_recordings_directory }}"
    owner: "{{ tvheadend_uid }}"
    group: "{{ tvheadend_gid }}"
  - name: dump
    comment: File dump
    guest_ok: true
    browseable: true
    public: true
    writable: true

# Defaults
docker_socket_path: /var/run/docker.sock
ansible_python_interpreter: /usr/bin/python3
docker_bridge_ip: 172.18.0.1
mysql_backup_container_image: databack/mysql-backup:latest
