---
# task file for organizr

- name: organizr directories
  file:
    path: "{{ organizr_data_directory }}"
    state: directory

- name: organizr docker container
  docker_container:
    name: "{{ organizr_container_name }}"
    image: "{{ organizr_container_image }}"
    recreate: true
    state: started
    container_default_behavior: no_defaults
    networks_cli_compatible: no
    restart_policy: unless-stopped
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    env:
      TZ: "{{ timezone }}"
      fpm: "true"
      branch: "{{ organizr_branch }}"
    volumes:
      - "{{ organizr_data_directory }}:/config"
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: "{{ organizr_expose }}"
      traefik.http.routers.organizr.tls: "true"
      traefik.http.routers.organizr.rule: "{{ organizr_traefik_rule }}"
      traefik.http.routers.organizr.tls.certresolver: letsencrypt
      traefik.http.services.organizr.loadbalancer.server.port: "80"
    networks:
      - name: "{{ traefik_network_name }}"
      - name: "{{ internal_network_name }}"
