---
# task file for organizr

- name: data directory
  file:
    path: "{{ organizr_data_directory }}"
    state: directory

- name: compose
  docker_compose:
    project_name: "{{ organizr_project_name }}"
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    definition:
      version: "3.5"
      networks:
        traefik_public:
          external: true
      services:
        organizr:
          container_name: "{{ organizr_container_name }}"
          image: "{{ organizr_container_image }}"
          restart: "{{ organizr_restart_policy }}"
          environment:
            - "TZ={{ timezone }}"
            - "fpm=true"
            - "branch={{ organizr_branch }}"
          volumes:
            - "{{ organizr_data_directory }}:/config"
            - /etc/localtime:/etc/localtime:ro
          labels:
            - "traefik.enable={{ organizr_expose }}"
            - "traefik.http.routers.organizr.tls=true"
            - "traefik.http.routers.organizr.rule={{ organizr_traefik_rule }}"
            - "traefik.http.routers.organizr.tls.certresolver=letsencrypt"
            - "traefik.http.services.organizr.loadbalancer.server.port=80"
          networks:
            - traefik_public
