---
# defaults file for sabnzbd

sabnzbd_container_name: sabnzbd
sabnzbd_container_image: "linuxserver/sabnzbd:latest"
sabnzbd_traefik_rule: "Host(`sabnzbd.{{ domain }}`)"
sabnzbd_expose: "true"
sabnzbd_data_directory: "{{ base_data_directory }}/sabnzbd"
