---
# task file for portainer

- name: config directory
  file:
    path: "{{ portainer_data_directory }}/config"
    state: directory

- name: admin password
  template:
    src: admin-password.j2
    dest: "{{ portainer_data_directory }}/admin-password"
    mode: 0400

- name: compose
  docker_compose:
    project_name: "{{ portainer_project_name }}"
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    definition:
      version: "3.5"
      networks:
        traefik_public:
          external: true
      services:
        portainer:
          container_name: "{{ portainer_container_name }}"
          image: "{{ portainer_container_image }}"
          restart: "{{ portainer_restart_policy }}"
          volumes:
            - "{{ docker_socket_path }}:/var/run/docker.sock"
            - "{{ portainer_data_directory }}/config:/data"
            - "{{ portainer_data_directory }}/admin-password:/tmp/admin-password:ro"
          labels:
            - "traefik.enable={{ portainer_expose }}"
            - "traefik.http.routers.portainer.tls=true"
            - "traefik.http.routers.portainer.rule={{ portainer_traefik_rule }}"
            - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
            - "traefik.http.services.portainer.loadbalancer.server.port=9000"
          networks:
            - traefik_public
          command: "-H unix://{{ docker_socket_path }} --admin-password-file /tmp/admin-password"
