---
# task file for nodered

- name: data directory
  file:
    path: "{{ nodered_data_directory }}"
    state: directory

- name: compose
  docker_compose:
    project_name: "{{ nodered_project_name }}"
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    definition:
      version: "3.5"
      networks:
        mqtt:
          external: true
        traefik_public:
          external: true
        mail:
          external: true
      services:
        nodered:
          container_name: "{{ nodered_container_name }}"
          image: "{{ nodered_container_image }}"
          restart: "{{ nodered_restart_policy }}"
          environment:
            - "TZ={{ timezone }}"
          volumes:
            - "{{ nodered_data_directory }}:/data"
          labels:
            - "traefik.enable={{ nodered_expose }}"
            - "traefik.http.routers.nodered.tls=true"
            - "traefik.http.routers.nodered.rule={{ nodered_traefik_rule }}"
            - "traefik.http.routers.nodered.middlewares=fauth@file"
            - "traefik.http.routers.nodered.tls.certresolver=letsencrypt"
            - "traefik.http.services.nodered.loadbalancer.server.port=1880"
          networks:
            - mail
            - mqtt
            - traefik_public
