---
# task file for duplicati

- name: data directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ base_data_directory }}"
    - "{{ duplicati_data_directory }}"
    - "{{ duplicati_backups_directory }}"
    - "{{ duplicati_temporary_directory }}"
    - "{{ db_backups_directory }}"

- name: docker container
  docker_container:
    name: "{{ duplicati_container_name }}"
    image: "{{ duplicati_container_image }}"
    recreate: true
    state: started
    container_default_behavior: no_defaults
    networks_cli_compatible: no
    restart_policy: "{{ duplicati_restart_policy }}"
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    env:
      TZ: "{{ timezone }}"
      PUID: "{{ duplicati_pid }}"
      PGID: "{{ duplicati_gid }}"
    volumes: "{{ duplicati_all_volumes }}"
    labels:
      traefik.enable: "{{ duplicati_expose }}"
      traefik.http.routers.duplicati.tls: "true"
      traefik.http.routers.duplicati.rule: "{{ duplicati_traefik_rule }}"
      traefik.http.routers.duplicati.middlewares: fauth@file
      traefik.http.routers.duplicati.tls.certresolver: letsencrypt
      traefik.http.services.duplicati.loadbalancer.server.port: "8200"
    networks:
      - name: "{{ traefik_network_name }}"
      - name: "{{ mail_network_name }}"
