---
# tasks file for mail

- name: data directory
  file:
    path: "{{ mail_data_directory }}"
    state: directory

- name: compose
  docker_compose:
    project_name: "{{ mail_project_name }}"
    definition:
      version: "3.5"
      services:
        mail:
          container_name: "{{ mail_container_name }}"
          image: "{{ mail_container_image }}"
          restart: "{{ mail_restart_policy }}"
          environment:
            - "TZ={{ timezone }}"
            - "RELAY_MYHOSTNAME=mail.{{ domain }}"
            - "RELAY_MYDOMAIN={{ domain }}"
            - "RELAY_MYNETWORKS={{ mail_subnet }}"
            - "RELAY_HOST={{ mail_relay_host }}"
            - "RELAY_LOGIN={{ mail_relay_user }}"
            - "RELAY_PASSWORD={{ mail_relay_password }}"
            - "RELAY_USE_TLS=yes"
            - "RELAY_TLS_CA=/ca-certificates.crt"
            - "RELAY_TLS_VERIFY=may"
            - "RELAY_MODE=ALLOW_NETAUTH_NODOMAIN"
            - "RELAY_POSTMASTER={{ mail_relay_postmaster }}"
            - "RELAY_STRICT_SENDER_MYDOMAIN=false"
          volumes:
            - "{{ mail_data_directory }}/data:/mail/data"
            - "/etc/ssl/certs/ca-certificates.crt:/ca-certificates.crt:ro"
          networks:
            - mail
      networks:
        mail:
          external: true
