---
# defaults file for netdata

netdata_project_name: netdata
netdata_container_name: netdata
netdata_container_image: "netdata/netdata:stable"
netdata_restart_policy: unless-stopped
netdata_traefik_rule: "Host(`netdata.{{ domain }}`)"
netdata_expose: "true"
netdata_data_directory: "{{ base_data_directory }}/netdata"
netdata_runtime_directory: "{{ base_runtime_directory }}/netdata"
