---
# task file for jupyter

- name: data directory
  file:
    path: "{{ jupyter_data_directory }}"
    state: directory
    owner: "1000"
    group: "1000"


- name: compose
  docker_compose:
    project_name: "{{ jupyter_project_name }}"
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    definition:
      version: "3.5"
      networks:
        traefik_public:
          external: true
      services:
        jupyter:
          container_name: "{{ jupyter_container_name }}"
          image: "{{ jupyter_container_image }}"
          restart: "{{ jupyter_restart_policy }}"
          command: "start-notebook.sh --ServerApp.custom_display_url='{{ jupyter_url }}' --ServerApp.token='' --ServerApp.password=''"
          user: root
          environment:
            - "TZ={{ timezone }}"
            - "JUPYTER_ENABLE_LAB={{ jupyter_lab_enabled }}"
            - "RESTARTABLE={{ jupyter_restartable }}"
            - "JUPYTER_TOKEN=''"
            - "GRANT_SUDO=yes"
          volumes:
            - "{{ jupyter_data_directory }}:/home/jovyan"
          labels:
            - "traefik.enable={{ jupyter_expose }}"
            - "traefik.http.routers.jupyter.tls=true"
            - "traefik.http.routers.jupyter.rule={{ jupyter_traefik_rule }}"
            - "traefik.http.routers.jupyter.middlewares=fauth@file"
            - "traefik.http.routers.jupyter.tls.certresolver=letsencrypt"
            - "traefik.http.services.jupyter.loadbalancer.server.port=8888"
          networks:
            - traefik_public
