---
# task file for sabnzbd

- name: data directory
  file:
    path: "{{ sabnzbd_data_directory }}"
    state: directory

- name: compose
  docker_compose:
    project_name: "{{ sabnzbd_project_name }}"
    definition:
      version: "3.5"
      networks:
        traefik_public:
          external: true
        mail:
          external: true
      services:
        sabnzbd:
          container_name: "{{ sabnzbd_container_name }}"
          image: "{{ sabnzbd_container_image }}"
          restart: "{{ sabnzbd_restart_policy }}"
          environment:
            - "TZ={{ timezone }}"
            - "PUID={{ media_uid }}"
            - "PGID={{ media_gid }}"
          volumes:
            - "{{ sabnzbd_data_directory }}:/config"
            - "{{ media_download_directory }}:/download"
            - "{{ media_nzb_watch_directory }}:/watch"
          labels:
            - "traefik.enable={{ sabnzbd_expose }}"
            - "traefik.http.routers.sabnzbd.tls=true"
            - "traefik.http.routers.sabnzbd.rule={{ sabnzbd_traefik_rule }}"
            - "traefik.http.routers.sabnzbd.middlewares=fauth@file"
            - "traefik.http.routers.sabnzbd.tls.certresolver=letsencrypt"
            - "traefik.http.services.sabnzbd.loadbalancer.server.port=8080"
          networks:
            - traefik_public
            - mail
