---
# task file for sabnzbd

- name: Create sabnzbd data directory
  file:
    path: "{{ sabnzbd_data_directory }}"
    state: directory

- name: sabnzbd docker container
  docker_container:
    name: "{{ sabnzbd_container_name }}"
    image: "{{ sabnzbd_container_image }}"
    recreate: true
    state: started
    container_default_behavior: no_defaults
    networks_cli_compatible: no
    restart_policy: unless-stopped
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    env:
      TZ: "{{ timezone }}"
      PUID: "{{ media_uid }}"
      PGID: "{{ media_gid }}"
    volumes:
      - "{{ sabnzbd_data_directory }}:/config"
      - "{{ media_download_directory }}:/download"
      - "{{ media_nzb_watch_directory }}:/watch"
    labels:
      traefik.enable: "{{ sabnzbd_expose }}"
      traefik.http.routers.sabnzbd.tls: "true"
      traefik.http.routers.sabnzbd.rule: "{{ sabnzbd_traefik_rule }}"
      traefik.http.routers.sabnzbd.middlewares: fauth@file
      traefik.http.routers.sabnzbd.tls.certresolver: letsencrypt
      traefik.http.services.sabnzbd.loadbalancer.server.port: "8080"
    networks:
      - name: "{{ traefik_network_name }}"
        aliases:
          - "{{ traefik_container_name }}"
      - name: "{{ internal_network_name }}"
      - name: "{{ mail_network_name }}"
