---
# task file for ombi

- name: data directory
  file:
    path: "{{ ombi_data_directory }}"
    state: directory
    owner: "{{ media_user.uid }}"
    group: "{{ media_user.group }}"

- name: compose
  docker_compose:
    project_name: "{{ ombi_project_name }}"
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    definition:
      version: "3.5"
      networks:
        traefik_public:
          external: true
        mail:
          external: true
        media:
          external: true
      services:
        ombi:
          container_name: "{{ ombi_container_name }}"
          image: "{{ ombi_container_image }}"
          restart: "{{ ombi_restart_policy }}"
          environment:
            - "TZ={{ timezone }}"
            - "PUID={{ media_user.uid }}"
            - "PGID={{ media_user.group }}"
          volumes:
            - "{{ ombi_data_directory }}:/config"
          labels:
            - "traefik.enable={{ ombi_expose }}"
            - "traefik.http.routers.ombi.tls=true"
            - "traefik.http.routers.ombi.rule={{ ombi_traefik_rule }}"
            - "traefik.http.routers.ombi.tls.certresolver=letsencrypt"
            - "traefik.http.services.ombi.loadbalancer.server.port=5000"
          networks:
            - traefik_public
            - media
            - mail
