---
# task file for ombi

- name: Create ombi data directory
  file:
    path: "{{ ombi_data_directory }}"
    state: directory
    owner: "{{ media_uid }}"
    group: "{{ media_gid }}"

- name: ombi docker container
  docker_container:
    name: "{{ ombi_container_name }}"
    image: "{{ ombi_container_image }}"
    recreate: true
    state: started
    container_default_behavior: no_defaults
    networks_cli_compatible: no
    restart_policy: unless-stopped
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    env:
      TZ: "{{ timezone }}"
      PUID: "{{ media_uid }}"
      PGID: "{{ media_gid }}"
    volumes:
      - "{{ ombi_data_directory }}:/config"
    labels:
      traefik.enable: "{{ ombi_expose }}"
      traefik.http.routers.ombi.tls: "true"
      traefik.http.routers.ombi.rule: "{{ ombi_traefik_rule }}"
      traefik.http.routers.ombi.tls.certresolver: letsencrypt
      traefik.http.services.ombi.loadbalancer.server.port: "3579"
    networks:
      - name: "{{ traefik_network_name }}"
      - name: "{{ internal_network_name }}"
      - name: "{{ mail_network_name }}"
