---
# task file for media

- name: user
  ansible.builtin.user:
    name: "{{ media_user_name }}"
    group: "{{ media_group_name }}"
    create_home: no
    shell: /bin/false
    state: present
  register: media_user

- name: directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ media_user.uid }}"
    group: "{{ media_user.group }}"
    mode: 0755
  loop:
    - "{{ media_directory }}/media/audiobooks"
    - "{{ media_directory }}/media/books"
    - "{{ media_directory }}/media/comics"
    - "{{ media_directory }}/media/magazines"
    - "{{ media_directory }}/media/movies"
    - "{{ media_directory }}/media/music"
    - "{{ media_directory }}/media/series"
    - "{{ media_directory }}/media/musicvideos"
    - "{{ media_directory }}/torrent/audiobooks"
    - "{{ media_directory }}/torrent/books"
    - "{{ media_directory }}/torrent/comics"
    - "{{ media_directory }}/torrent/magazines"
    - "{{ media_directory }}/torrent/movies"
    - "{{ media_directory }}/torrent/music"
    - "{{ media_directory }}/torrent/series"
    - "{{ media_directory }}/torrent/musicvideos"
    - "{{ media_directory }}/usenet/audiobooks"
    - "{{ media_directory }}/usenet/books"
    - "{{ media_directory }}/usenet/comics"
    - "{{ media_directory }}/usenet/magazines"
    - "{{ media_directory }}/usenet/movies"
    - "{{ media_directory }}/usenet/music"
    - "{{ media_directory }}/usenet/series"
    - "{{ media_directory }}/usenet/musicvideos"
    - "{{ media_directory }}/usenet/incomplete"
    - "{{ media_directory }}/usenet/complete"

- name: network
  community.docker.docker_network:
    name: media
    driver: overlay
    internal: true
    attachable: true
