---
# tasks file for docker

- name: docker
  when: "'nodeps' not in ansible_run_tags"
  block:
    - name: Add Docker GPG apt key
      apt_key:
        url: "https://download.docker.com/linux/{{ linux_distribution }}/gpg"
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/{{ linux_distribution }} {{ linux_release }} stable"

    - name: Update package cache
      apt:
        update_cache: true

    - name: Install packages
      apt:
        state: latest
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - python3-pexpect
          - docker-ce
          - docker-compose

    - name: Start and enable docker daemon
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Initialize docker swarm
      community.docker.docker_swarm:
        state: present

    - name: Create internal network
      docker_network:
        name: "{{ internal_network_name }}"
        attachable: true
        state: present
        driver: overlay
        internal: true

    - name: Create mail network
      docker_network:
        name: "{{ mail_network_name }}"
        ipam_config:
          - subnet: "{{ mail_subnet }}"
        attachable: true
        state: present
        driver: overlay
        internal: false

    - name: Add host shim device
      shell: "ip link add {{ macvlan_host_shim_name }} link eno1 type macvlan mode bridge || true"

    - name: Set address of host shim device
      shell: "ip addr add {{ macvlan_host_shim_address }}/32 dev mynet-shim || true"

    - name: Bring up host shim device
      shell: "ip link set mynet-shim up || true"

    - name: Bring up host shim device
      shell: "ip route add {{ macvlan_range }} dev {{ macvlan_host_shim_name }} || true"

    - name: Create macvlan network
      docker_network:
        name: "{{ macvlan_network_name }}"
        ipam_config:
          - subnet: "{{ macvlan_subnet }}"
            iprange: "{{ macvlan_range }}"
            gateway: "{{ macvlan_gateway }}"
            aux_addresses:
              host: "{{ macvlan_host_shim_address }}"
        attachable: true
        state: present
        driver: macvlan
        driver_options:
          parent: "{{ macvlan_parent }}"
        internal: false
        enable_ipv6: false

    # - name: Enable promiscuous mode
    #   command: "ip link set {{ item }} promisc on || true"
    #   loop:
    #     - "{{ macvlan_parent }}"
        # - "{{ macvlan_network_name }}"
        # - "{{ macvlan_host_shim_name }}"

    - name: Update facts
      setup:

    - name: Install docker module for Python
      pip:
        name: docker
        virtualenv_python: python3
