---
# defaults file for sonarr

sonarr_project_name: "{{ media_project_name }}"
sonarr_container_name: sonarr
sonarr_container_image: "ghcr.io/hotio/sonarr:latest"
sonarr_restart_policy: unless-stopped
sonarr_traefik_rule: "Host(`sonarr.{{ domain }}`)"
sonarr_expose: "true"
sonarr_data_directory: "{{ base_data_directory }}/sonarr"
