---
# task file for unmanic

- name: directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ media_user.uid }}"
    group: "{{ media_user.group }}"
  loop:
    - "{{ unmanic_runtime_directory }}"
    - "{{ unmanic_data_directory }}"

- name: compose
  docker_compose:
    project_name: "{{ unmanic_project_name }}"
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    definition:
      version: "3.5"
      networks:
        traefik_public:
          external: true
      services:
        unmanic:
          container_name: "{{ unmanic_container_name }}"
          image: "{{ unmanic_container_image }}"
          restart: "{{ unmanic_restart_policy }}"
          environment:
            - "TZ={{ timezone }}"
            - "PUID={{ media_user.uid }}"
            - "PGID={{ media_user.group }}"
            - "UMASK={{ media_umask }}"
          volumes:
            - "{{ unmanic_data_directory }}:/config"
            - "{{ unmanic_runtime_directory }}:/tmp/unmanic"
            - "{{ media_directory }}/media:/data/media"
          labels:
            - "traefik.enable={{ unmanic_expose }}"
            - "traefik.http.routers.unmanic.tls=true"
            - "traefik.http.routers.unmanic.rule={{ unmanic_traefik_rule }}"
            - "traefik.http.routers.unmanic.middlewares=fauth@file"
            - "traefik.http.routers.unmanic.tls.certresolver=letsencrypt"
            - "traefik.http.services.unmanic.loadbalancer.server.port=8888"
          networks:
            - traefik_public
