---
# tasks file for homeassistant

- name: data directory
  file:
    path: "{{ homeassistant_data_directory }}"
    state: directory

- name: compose
  docker_compose:
    project_name: "{{ homeassistant_project_name }}"
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    definition:
      version: "3.5"
      services:
        homeassistant:
          container_name: "{{ homeassistant_container_name }}"
          image: "{{ homeassistant_container_image }}"
          restart: "{{ homeassistant_restart_policy }}"
          environment:
            - "TZ={{ timezone }}"
          volumes:
            - "{{ homeassistant_data_directory }}:/config"
          labels:
            - "traefik.enable={{ homeassistant_expose }}"
            - "traefik.http.routers.homeassistant.tls=true"
            - "traefik.http.routers.homeassistant.rule={{ homeassistant_traefik_rule }}"
            - "traefik.http.routers.homeassistant.tls.certresolver=letsencrypt"
            - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
          network_mode: host
          extra_hosts:
            - "host.docker.internal:{{ host_ip }}"
