---
# defaults file for torrent

torrent_project_name: "{{ media_project_name }}"
torrent_container_name: torrent
torrent_container_image: "ghcr.io/hotio/rflood:release"
torrent_restart_policy: unless-stopped
torrent_traefik_rule: "Host(`torrent.{{ domain }}`)"
torrent_expose: "true"
torrent_data_directory: "{{ base_data_directory }}/torrent"
torrent_vpn_enabled: "true"
torrent_vpn_lan_network: ""
torrent_vpn_conf: "wg0"
torrent_vpn_additional_ports: ""
torrent_privoxy_enabled: "false"
torrent_flood_auth: "false"
torrent_disable_ipv6: "0"
torrent_wireguard: |
  [Interface]
  PrivateKey = supersecretprivatekey
  Address = xx.xx.xxx.xxx/32
  DNS = 1.1.1.1

  [Peer]
  PublicKey = publickey
  AllowedIPs = 0.0.0.0/0
  Endpoint = xxx.x.xxx.x:51820
