---
# task file for calibre_web

- name: data directory
  file:
    path: "{{ calibre_web_data_directory }}"
    state: directory

- name: compose
  docker_compose:
    project_name: "{{ calibre_web_project_name }}"
    definition:
      version: "3.5"
      networks:
        traefik_public:
          external: true
        mail:
          external: true
        internal:
          external: true
      services:
        calibre_web:
          container_name: "{{ calibre_web_container_name }}"
          image: "{{ calibre_web_container_image }}"
          restart: "{{ calibre_web_restart_policy }}"
          environment:
            - "TZ={{ timezone }}"
            - "PUID={{ media_uid }}"
            - "PGID={{ media_gid }}"
            - "DOCKER_MODS=linuxserver/calibre-web:calibre"
          volumes:
            - "{{ calibre_web_data_directory }}:/config"
            - "{{ media_books_directory }}:/books"
            - "{{ shared_directory }}:/shared:ro"
          labels:
            - "traefik.enable={{ calibre_web_expose }}"
            - "traefik.http.routers.calibre_web.tls=true"
            - "traefik.http.routers.calibre_web.rule={{ calibre_web_traefik_rule }}"
            - "traefik.http.routers.calibre_web.middlewares=fauth@file"
            - "traefik.http.routers.calibre_web.tls.certresolver=letsencrypt"
            - "traefik.http.services.calibre_web.loadbalancer.server.port=8083"
          networks:
            - traefik_public
            - internal
            - mail
