---
# task file for wallabag_kindle

- name: data directory
  file:
    path: "{{ wallabag_kindle_data_directory }}"
    state: directory

- name: compose
  docker_compose:
    project_name: "{{ wallabag_kindle_project_name }}"
    pull: "{{ 'upgrade' in ansible_run_tags }}"
    definition:
      version: "3.5"
      networks:
        traefik_public:
          external: true
        mail:
          external: true
      services:
        wallabag_kindle:
          container_name: "{{ wallabag_kindle_container_name }}"
          image: "{{ wallabag_kindle_container_image }}"
          environment:
            - "TZ={{ timezone }}"
            - "WALLABAG_HOST={{ wallabag_kindle_wallabag_host }}"
            - "DB_URI={{ wallabag_kindle_db_uri }}"
            - "CLIENT_ID={{ wallabag_kindle_client_id }}"
            - "CLIENT_SECRET={{ wallabag_kindle_client_secret }}"
            - "DOMAIN={{ wallabag_kindle_domain }}"
            - "SMTP_FROM={{ wallabag_kindle_smtp_from }}"
            - "SMTP_HOST={{ wallabag_kindle_smtp_host }}"
            - "SMTP_PORT={{ wallabag_kindle_smtp_port }}"
            - "SMTP_USER={{ wallabag_kindle_smtp_user }}"
            - "SMTP_PASSWD={{ wallabag_kindle_smtp_passwd }}"
            - "TAG={{ wallabag_kindle_tag }}"
            - "REFRESH_GRACE={{ wallabag_kindle_refresh_grace }}"
            - "CONSUME_INTERVAL={{ wallabag_kindle_consume_interval }}"
            - "INTERFACE_HOST={{ wallabag_kindle_interface_host }}"
            - "INTERFACE_PORT={{ wallabag_kindle_interface_port }}"
          restart: "{{ wallabag_kindle_restart_policy }}"
          volumes:
            - "{{ wallabag_kindle_data_directory }}:/data"
          labels:
            - "traefik.enable={{ wallabag_kindle_expose }}"
            - "traefik.http.routers.wallabag_kindle.tls=true"
            - "traefik.http.routers.wallabag_kindle.rule={{ wallabag_kindle_traefik_rule }}"
            - "traefik.http.routers.sonarr.middlewares=fauth@file"
            - "traefik.http.routers.wallabag_kindle.tls.certresolver=letsencrypt"
            - "traefik.http.services.wallabag_kindle.loadbalancer.server.port={{ wallabag_kindle_interface_port }}"
          networks:
            - traefik_public
            - mail
