---

- name: config directory
  file:
    path: "{{ wireguard_config_directory }}"
    owner: "{{ wireguard_uid }}"
    group: "{{ wireguard_gid }}"
    state: directory

- name: compose
  docker_compose:
    project_name: "{{ wireguard_project_name }}"
    definition:
      version: "3.5"
      services:
        wireguard:
          container_name: "{{ wireguard_container_name }}"
          image: "{{ wireguard_container_image }}"
          restart: "{{ wireguard_restart_policy }}"
          environment:
            - "TZ={{ timezone }}"
            - "PUID={{ wireguard_uid }}"
            - "PGID={{ wireguard_gid }}"
            - "SERVERURL={{ wireguard_url }}"
            - "SERVERPORT={{ wireguard_port }}"
            - "PEERS={{ wireguard_peers }}"
            - "PEERDNS={{ wireguard_peerdns }}"
            - "INTERNAL_SUBNET={{ wireguard_internal_subnet }}"
            - "ALLOWEDIPS={{ wireguard_allowed_ips }}"
          ports:
            - "{{ wireguard_port }}:51820/udp"
          volumes:
            - "{{ wireguard_config_directory }}:/config"
            - "{{ wireguard_modules_directory }}:/lib/modules"
          cap_add:
            - net_admin
            - sys_module
