---

- name: directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ pihole_data_directory }}/config"
    - "{{ pihole_runtime_directory }}"

- name: resolv.conf
  copy:
    src: resolv.conf
    force: no
    dest: "{{ pihole_data_directory }}/resolv.conf"

- name: log file
  file:
    path: "{{ pihole_runtime_directory }}/pihole.log"
    state: touch
    force: no
    mode: 0600

- name: extra hosts file
  template:
    src: hosts.conf.j2
    dest: "{{ pihole_data_directory }}/hosts.conf"

- name: compose
  docker_compose:
    project_name: "{{ pihole_project_name }}"
    definition:
      version: "3.5"
      networks:
        traefik_public:
          external: true
      services:
        pihole:
          container_name: "{{ pihole_container_name }}"
          image: "{{ pihole_container_image }}"
          restart: "{{ pihole_restart_policy }}"
          environment:
            - "TZ={{ timezone }}"
            - "ServerIP={{ host_ip }}"
            - "VIRTUAL_HOST={{ domain }}"
            - "WEBPASSWORD={{ pihole_password }}"
            - "DNSMASQ_LISTENING=all"
          ports:
            - "53:53/tcp"
            - "53:53/udp"
          volumes:
            - "{{ pihole_data_directory }}/config:/etc/pihole"
            - "{{ pihole_runtime_directory }}/pihole.log:/var/log/pihole.log"
            - "{{ pihole_data_directory }}/hosts.conf:/etc/dnsmasq.d/02-hosts.conf"
            - "{{ pihole_data_directory }}/resolv.conf:/etc/resolv.conf"
          labels:
            - "traefik.enable={{ pihole_expose }}"
            - "traefik.http.routers.pihole.tls=true"
            - "traefik.http.routers.pihole.tls.certresolver=letsencrypt"
            - "traefik.http.routers.pihole.rule=HostRegexp(`{any:.*}`)"
            - "traefik.http.services.pihole.loadbalancer.server.port=80"
            - "traefik.http.routers.pihole-admin.rule={{ pihole_traefik_rule }}"
            - "traefik.http.middlewares.add-admin.addprefix.prefix=/admin"
            - "traefik.http.routers.pihole-admin.middlewares=frame-allow@file,add-admin@docker"
          networks:
            traefik_public:
              aliases:
                - "{{ pihole_container_name }}"
          extra_hosts:
            "host.docker.internal": "{{ host_ip }}"
          dns:
            - 127.0.0.1
            - 1.1.1.1
